/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.rightnow.logging.events;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** An error for an event */
@org.apache.avro.specific.AvroGenerated
public class error extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5895520610380653484L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"error\",\"namespace\":\"org.rightnow.logging.events\",\"doc\":\"An error for an event\",\"fields\":[{\"name\":\"field\",\"type\":\"string\",\"doc\":\"The field the error is on\"},{\"name\":\"reason\",\"type\":\"string\",\"doc\":\"The reason the field is causing an error\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** The field the error is on */
  @Deprecated public CharSequence field;
  /** The reason the field is causing an error */
  @Deprecated public CharSequence reason;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public error() {}

  /**
   * All-args constructor.
   * @param field The field the error is on
   * @param reason The reason the field is causing an error
   */
  public error(CharSequence field, CharSequence reason) {
    this.field = field;
    this.reason = reason;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return field;
    case 1: return reason;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: field = (CharSequence)value$; break;
    case 1: reason = (CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'field' field.
   * @return The field the error is on
   */
  public CharSequence getField() {
    return field;
  }

  /**
   * Sets the value of the 'field' field.
   * The field the error is on
   * @param value the value to set.
   */
  public void setField(CharSequence value) {
    this.field = value;
  }

  /**
   * Gets the value of the 'reason' field.
   * @return The reason the field is causing an error
   */
  public CharSequence getReason() {
    return reason;
  }

  /**
   * Sets the value of the 'reason' field.
   * The reason the field is causing an error
   * @param value the value to set.
   */
  public void setReason(CharSequence value) {
    this.reason = value;
  }

  /**
   * Creates a new error RecordBuilder.
   * @return A new error RecordBuilder
   */
  public static org.rightnow.logging.events.error.Builder newBuilder() {
    return new org.rightnow.logging.events.error.Builder();
  }

  /**
   * Creates a new error RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new error RecordBuilder
   */
  public static org.rightnow.logging.events.error.Builder newBuilder(org.rightnow.logging.events.error.Builder other) {
    return new org.rightnow.logging.events.error.Builder(other);
  }

  /**
   * Creates a new error RecordBuilder by copying an existing error instance.
   * @param other The existing instance to copy.
   * @return A new error RecordBuilder
   */
  public static org.rightnow.logging.events.error.Builder newBuilder(org.rightnow.logging.events.error other) {
    return new org.rightnow.logging.events.error.Builder(other);
  }

  /**
   * RecordBuilder for error instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<error>
    implements org.apache.avro.data.RecordBuilder<error> {

    /** The field the error is on */
    private CharSequence field;
    /** The reason the field is causing an error */
    private CharSequence reason;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.rightnow.logging.events.error.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.field)) {
        this.field = data().deepCopy(fields()[0].schema(), other.field);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.reason)) {
        this.reason = data().deepCopy(fields()[1].schema(), other.reason);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing error instance
     * @param other The existing instance to copy.
     */
    private Builder(org.rightnow.logging.events.error other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.field)) {
        this.field = data().deepCopy(fields()[0].schema(), other.field);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.reason)) {
        this.reason = data().deepCopy(fields()[1].schema(), other.reason);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'field' field.
      * The field the error is on
      * @return The value.
      */
    public CharSequence getField() {
      return field;
    }

    /**
      * Sets the value of the 'field' field.
      * The field the error is on
      * @param value The value of 'field'.
      * @return This builder.
      */
    public org.rightnow.logging.events.error.Builder setField(CharSequence value) {
      validate(fields()[0], value);
      this.field = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'field' field has been set.
      * The field the error is on
      * @return True if the 'field' field has been set, false otherwise.
      */
    public boolean hasField() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'field' field.
      * The field the error is on
      * @return This builder.
      */
    public org.rightnow.logging.events.error.Builder clearField() {
      field = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'reason' field.
      * The reason the field is causing an error
      * @return The value.
      */
    public CharSequence getReason() {
      return reason;
    }

    /**
      * Sets the value of the 'reason' field.
      * The reason the field is causing an error
      * @param value The value of 'reason'.
      * @return This builder.
      */
    public org.rightnow.logging.events.error.Builder setReason(CharSequence value) {
      validate(fields()[1], value);
      this.reason = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'reason' field has been set.
      * The reason the field is causing an error
      * @return True if the 'reason' field has been set, false otherwise.
      */
    public boolean hasReason() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'reason' field.
      * The reason the field is causing an error
      * @return This builder.
      */
    public org.rightnow.logging.events.error.Builder clearReason() {
      reason = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public error build() {
      try {
        error record = new error();
        record.field = fieldSetFlags()[0] ? this.field : (CharSequence) defaultValue(fields()[0]);
        record.reason = fieldSetFlags()[1] ? this.reason : (CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
